
try {
	throw 'Erreur';
} catch(e) {
	console.log('Exception :', e);
}

// Lancez un exception de type Error.